-- MySQL Script generated by MySQL Workbench
-- 09/28/15 22:40:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema netin
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `netin` ;

-- -----------------------------------------------------
-- Schema netin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `netin` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `netin` ;

-- -----------------------------------------------------
-- Table `netin`.`types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`types` ;

CREATE TABLE IF NOT EXISTS `netin`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  `updated` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netin`.`locals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`locals` ;

CREATE TABLE IF NOT EXISTS `netin`.`locals` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  `lat` INT NULL COMMENT '',
  `lon` INT NULL COMMENT '',
  `status` TINYINT(1) NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  `updated` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netin`.`organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`organizations` ;

CREATE TABLE IF NOT EXISTS `netin`.`organizations` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `telephone` INT NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  `logo` VARCHAR(45) NULL COMMENT '',
  `url` VARCHAR(45) NULL COMMENT '',
  `local_id` INT NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  `updated` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_organizations_local_idx` (`local_id` ASC)  COMMENT '',
  CONSTRAINT `fk_organizations_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `netin`.`locals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netin`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`events` ;

CREATE TABLE IF NOT EXISTS `netin`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `date` DATETIME NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  `status` TINYINT(1) NULL COMMENT '',
  `organization_id` INT NOT NULL COMMENT '',
  `local_id` INT NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  `updated` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_events_organization1_idx` (`organization_id` ASC)  COMMENT '',
  INDEX `fk_events_local1_idx` (`local_id` ASC)  COMMENT '',
  CONSTRAINT `fk_events_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `netin`.`organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_local1`
    FOREIGN KEY (`local_id`)
    REFERENCES `netin`.`locals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netin`.`type_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`type_events` ;

CREATE TABLE IF NOT EXISTS `netin`.`type_events` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `type_id` INT NOT NULL COMMENT '',
  `event_id` INT NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_type_events_event1_idx` (`event_id` ASC)  COMMENT '',
  INDEX `fk_type_events_type1_idx` (`type_id` ASC)  COMMENT '',
  CONSTRAINT `fk_type_events_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `netin`.`types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_type_events_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `netin`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netin`.`event_locals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`event_locals` ;

CREATE TABLE IF NOT EXISTS `netin`.`event_locals` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `event_id` INT NOT NULL COMMENT '',
  `local_id` INT NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_event_locals_local1_idx` (`local_id` ASC)  COMMENT '',
  INDEX `fk_event_locals_event1_idx` (`event_id` ASC)  COMMENT '',
  CONSTRAINT `fk_event_locals_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `netin`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_locals_local1`
    FOREIGN KEY (`local_id`)
    REFERENCES `netin`.`locals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netin`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`users` ;

CREATE TABLE IF NOT EXISTS `netin`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(64) NOT NULL COMMENT '', 
  `telephone` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  `active` TINYINT(1) NULL COMMENT '',
  `role` VARCHAR(45) NULL COMMENT '',
  `privilege` INT NULL COMMENT '',
  `last_login` DATETIME NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  `updated` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netin`.`event_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`event_users` ;

CREATE TABLE IF NOT EXISTS `netin`.`event_users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `event_id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_event_users_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_event_users_event1_idx` (`event_id` ASC)  COMMENT '',
  CONSTRAINT `fk_event_users_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `netin`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_users_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `netin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netin`.`user_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`user_users` ;

CREATE TABLE IF NOT EXISTS `netin`.`user_users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `user_id1` INT NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_user_users_user2_idx` (`user_id1` ASC)  COMMENT '',
  INDEX `fk_user_users_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_users_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `netin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_users_user2`
    FOREIGN KEY (`user_id1`)
    REFERENCES `netin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netin`.`interests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`interests` ;

CREATE TABLE IF NOT EXISTS `netin`.`interests` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `slug` VARCHAR(255) NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  `updated` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netin`.`user_interests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`user_interests` ;

CREATE TABLE IF NOT EXISTS `netin`.`user_interests` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `interest_id` INT NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_user_interests_interest1_idx` (`interest_id` ASC)  COMMENT '',
  INDEX `fk_user_interests_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_interests_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `netin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_interests_interest1`
    FOREIGN KEY (`interest_id`)
    REFERENCES `netin`.`interests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netin`.`user_organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netin`.`user_organizations` ;

CREATE TABLE IF NOT EXISTS `netin`.`user_organizations` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `organization_id` INT NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_user_organizations_organization1_idx` (`organization_id` ASC)  COMMENT '',
  INDEX `fk_user_organizations_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_organizations_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `netin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_organizations_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `netin`.`organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;